behaviors:
  CarDrive: &car-drive
    trainer_type: ppo
  
    # Trainer configs common to PPO/SAC (excluding reward signals)
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      learning_rate_schedule: linear      
      # PPO-specific configs
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
  
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 128
      num_layers: 2
      # memory
      memory:
        sequence_length: 64
        memory_size: 128
          
    max_steps: 1.0e6
    time_horizon: 64
    summary_freq: 10000
    threaded: true
  
    reward_signals:
      # environment reward
      extrinsic:
        strength: 1.0
        gamma: 0.99

  CarDriveStraight:
    <<: *car-drive
          
  CarDriveSelfPlayVictim:
    <<: *car-drive
    
    # self-play
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.7
      save_steps: 20000
      team_change: 100000
      swap_steps: 50000

  CarDriveSelfPlayAdversary:
    <<: *car-drive

    # self-play
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.7
      save_steps: 20000
      team_change: 100000
      swap_steps: 50000
  